### ISSUE TITLE
kn.split has annoying defaults

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#29]
In the `cloudknot_parallelization_demo.ipynb`, I ran 

``` python
for prefix in to_track:
    kn.split(prefix, remote_folder=remote_folder)
```

for a long time (had to download images), only to have it fail on upload because `bucket='nancelab.publicfiles'`. This meant I had to re-download the entire S3 bucket.

**Comment by stsievert** [comment]
It's also annoying this is necessary – `kn.split` doesn't do much, and the notebook wastes a lot of time (and bandwidth) on this.

**Comment by ccurtis7** [comment]
Another default setting problem-- I will get rid of the default behavior, similar to other functions we've address, so that the user is forced to specify a bucket. There isn't really a good default for this, after all. The user needs to enter one.

Regarding notebook workflow, yes, this step is the bottleneck in the process. I do have a function that performs all three steps (splitting, tracking, and downstream calculations) all in a single function, but it can crash your AWS instances if you don't have just the right settings, and also requires a larger EC2 instances (since you'd be tracking multiple split videos on a single machine).

For the purposes of demoing Cloudknot, I will skip the splitting step (since the split images are already all available in `nancelab.publicfiles`. This should address this issue.

**Comment by stsievert** [comment]
> so that the user is forced to specify a bucket.

:+1:

>  I will skip the splitting step (since the split images are already all available in nancelab.publicfiles. This should address this issue.

:+1:

**Comment by ccurtis7** [comment]
As of now, I don't have a better way of speeding up the splitting process. Ideally, it would be nice if I didn't have to split the images at all, but if you're video files are too big, `ij.track` crashes as you eat up memory. The easiest solution is to split the images.

**Comment by ccurtis7** [comment]
So, I made the above changes, as explained.

I also double-checked that the commands to AWS are working, so you should be good to go once you get there.

I also made sure the downstream calculation functions are working. To make your life and other users easier, I added in some functionality to only plot a subset of the data (and made that the default) so you don't wait forever for it to plot. I have a for loop that plots each trajectory. If you have > 10000 trajectories, that's a nasty for loop. 


It should be good to go. I apologize for all these hiccups.

**Comment by stsievert** [comment]
It looks like `kn.split` is deterministic and runs some simple code each time ([imagej.py#L121-L127]). Could these be saved on the `nancelab.publicfiles` bucket somewhere so `kn.split` doesn't have to be called each time the `cloudknot_parallelization_demo.ipynb` is run?

If the notebook doesn't run without some modification (e.g., changing `bucket`), it'd be nice to have the output in the notebook.

[imagej.py#L121-L127]:https://github.com/ccurtis7/diff_classifier/blob/fe8adf808878779e6e9694aa231a5bcb73d14f58/diff_classifier/imagej.py#L121-L127

**Comment by ccurtis7** [comment]
I already have the split image files uploaded to `nancelab.publicfiles`, so `kn.split` doesn't have to be run.

I will go ahead and include the output, so users can see what happens when `kn.split` is run.

**Comment by ccurtis7** [comment]
I want to note one thing too @stsievert, so you can anticipate it. The call to `kn.assemble_msds` again doesn't scale well if you have a ton of trajectories in your file (which the example videos do). It has to call on some nonlinear solvers that can't be easily parallelized using numpy, so it's unavoidable.

From a practical perspective, I solve this problem by sending individual instances to cloudknot. Since this toy example is only processing two images, I don't think you need to do that. But it still eats up time. Mine is taking upwards of 30 mins atm.

**Comment by ccurtis7** [comment]
Done. I've included the output in the notebook!
