### ISSUE TITLE
Rows/cols are assumed to be 4 in knotlets.py (and related documentation)

### ISSUE THREAD

**Issue by stsievert** [ccurtis7/diff_classifier#31]
I found two cases, in `split` and `assemble_msds`:

https://github.com/ccurtis7/diff_classifier/blob/483b25a4bf71a21d95d4145f41b247b6509d9cc1/diff_classifier/knotlets.py#L182-L184

https://github.com/ccurtis7/diff_classifier/blob/483b25a4bf71a21d95d4145f41b247b6509d9cc1/diff_classifier/knotlets.py#L55-L57

I think these functions read from files written by `imagej.partition_im`, which may not split images into 4 sections each.

Additionally, the documentation isn't super clear in the `assemble_msds` docstring -- there's no clear link to where the `row` and `col` values come from, `knotlets.split`.

**Comment by stsievert** [comment]
I'd clarify also clarify what `imagej.split` does, that it writes out files. Is there anyway you could gather the names from the S3 bucket before downloading? That'd resolve most of this issue – the API would be simplified (no more `rows`/`cols`), and the definition of `names` wouldn't be required.

**Comment by ccurtis7** [comment]
I added in more documentation at the top of `knotlets.py` to explain overall flow of how the functions work together.

I added in more documentation into `kn.split`, `kn.track`, and `kn.assemble_msds` clarifying their use with Cloudknot and how they work together.

I also added in your recommended changes to `kn.assemble_msds` such that I can extract `names`, `rows`, and `cols` from S3 rather than entering them as inputs.
